# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  commands:
    # Install documentation dependencies
    - pip install -r docs/en/requirements.txt
    # Build the correct language based on the RTD project language setting
    - >-
      if [ "$READTHEDOCS_LANGUAGE" = "fr" ]; then
        mkdocs build -f mkdocs-fr.yml -d $READTHEDOCS_OUTPUT/html;
      else
        mkdocs build -f mkdocs.yml -d $READTHEDOCS_OUTPUT/html;
      fi