# Generated by Tenxyte — R20: Migration decomposition
# Core models: Application, User

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("access_key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("access_secret", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "applications",
                "ordering": ["name"],
                "abstract": False,
                "swappable": "TENXYTE_APPLICATION_MODEL",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=191, null=True, unique=True)),
                ("phone_country_code", models.CharField(blank=True, max_length=5, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=20, null=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("google_id", models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_phone_verified", models.BooleanField(default=False)),
                ("totp_secret", models.CharField(blank=True, max_length=32, null=True)),
                ("is_2fa_enabled", models.BooleanField(default=False)),
                ("backup_codes", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "is_banned",
                    models.BooleanField(
                        default=False, help_text="Permanent ban (manual admin action). Cannot be auto-lifted."
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete for GDPR compliance. Account is anonymized but kept for audit.",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "anonymization_token",
                    models.CharField(
                        blank=True,
                        help_text="Token used to identify anonymized accounts for audit purposes.",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "max_sessions",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum concurrent sessions allowed (0 = unlimited)"
                    ),
                ),
                (
                    "max_devices",
                    models.PositiveIntegerField(default=1, help_text="Maximum unique devices allowed (0 = unlimited)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "abstract": False,
                "swappable": "TENXYTE_USER_MODEL",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone_country_code", "phone_number"], name="users_phone_c_e3358a_idx"),
        ),
    ]
