# Generated by Django 6.0.2 on 2026-02-16 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("access_key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("access_secret", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "applications",
                "ordering": ["name"],
                "abstract": False,
                "swappable": "TENXYTE_APPLICATION_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.TENXYTE_PERMISSION_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "permissions",
                "ordering": ["code"],
                "abstract": False,
                "swappable": "TENXYTE_PERMISSION_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, related_name="roles", to=settings.TENXYTE_PERMISSION_MODEL),
                ),
            ],
            options={
                "db_table": "roles",
                "ordering": ["name"],
                "abstract": False,
                "swappable": "TENXYTE_ROLE_MODEL",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=191, null=True, unique=True)),
                ("phone_country_code", models.CharField(blank=True, max_length=5, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=20, null=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("google_id", models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_phone_verified", models.BooleanField(default=False)),
                ("totp_secret", models.CharField(blank=True, max_length=32, null=True)),
                ("is_2fa_enabled", models.BooleanField(default=False)),
                ("backup_codes", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("is_banned", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("anonymization_token", models.CharField(blank=True, max_length=64, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "max_sessions",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum concurrent sessions allowed (0 = unlimited)"
                    ),
                ),
                (
                    "max_devices",
                    models.PositiveIntegerField(default=1, help_text="Maximum unique devices allowed (0 = unlimited)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "direct_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="users_direct", to=settings.TENXYTE_PERMISSION_MODEL
                    ),
                ),
                ("roles", models.ManyToManyField(blank=True, related_name="users", to=settings.TENXYTE_ROLE_MODEL)),
            ],
            options={
                "db_table": "users",
                "abstract": False,
                "swappable": "TENXYTE_USER_MODEL",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("login_failed", "Login Failed"),
                            ("logout", "Logout"),
                            ("logout_all", "Logout All Devices"),
                            ("token_refresh", "Token Refresh"),
                            ("password_change", "Password Changed"),
                            ("password_reset_request", "Password Reset Requested"),
                            ("password_reset_complete", "Password Reset Completed"),
                            ("2fa_enabled", "2FA Enabled"),
                            ("2fa_disabled", "2FA Disabled"),
                            ("2fa_backup_used", "2FA Backup Code Used"),
                            ("account_created", "Account Created"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("email_verified", "Email Verified"),
                            ("phone_verified", "Phone Verified"),
                            ("role_assigned", "Role Assigned"),
                            ("role_removed", "Role Removed"),
                            ("permission_changed", "Permission Changed"),
                            ("app_created", "Application Created"),
                            ("app_credentials_regenerated", "Application Credentials Regenerated"),
                            ("account_deleted", "Account Deleted"),
                            ("suspicious_activity", "Suspicious Activity Detected"),
                            ("session_limit_exceeded", "Session Limit Exceeded"),
                            ("device_limit_exceeded", "Device Limit Exceeded"),
                            ("new_device_detected", "New Device Detected"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.TENXYTE_APPLICATION_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token_jti", models.CharField(db_index=True, max_length=191, unique=True)),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "blacklisted_tokens",
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("identifier", models.CharField(db_index=True, max_length=191)),
                ("ip_address", models.GenericIPAddressField()),
                ("success", models.BooleanField(default=False)),
                ("failure_reason", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.TENXYTE_APPLICATION_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "login_attempts",
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=64)),
                (
                    "otp_type",
                    models.CharField(
                        choices=[
                            ("email_verification", "Email Verification"),
                            ("phone_verification", "Phone Verification"),
                            ("password_reset", "Password Reset"),
                            ("login_2fa", "Login 2FA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "otp_codes",
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("password_hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(db_index=True, max_length=191, unique=True)),
                ("device_info", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("is_revoked", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.TENXYTE_APPLICATION_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "refresh_tokens",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone_country_code", "phone_number"], name="users_phone_c_e3358a_idx"),
        ),
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("confirmation_sent", "Confirmation Sent"), ("confirmed", "Confirmed"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("confirmation_token", models.CharField(help_text="Secure token for email confirmation", max_length=64, unique=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("grace_period_ends_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True, help_text="Optional reason for deletion request")),
                ("admin_notes", models.TextField(blank=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deletion_requests", to=settings.AUTH_USER_MODEL)),
                ("processed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processed_deletions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "account_deletion_requests",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="account_del_user_status_idx"),
                    models.Index(fields=["status", "grace_period_ends_at"], name="account_del_status_grace_idx"),
                    models.Index(fields=["confirmation_token"], name="account_del_token_idx"),
                ],
            },
        ),
    ]
