# Generated by Tenxyte — R20: Migration decomposition
# RBAC models: Permission, Role, OrganizationRole
# and their M2M relationships to User

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0001_core"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.TENXYTE_PERMISSION_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "permissions",
                "ordering": ["code"],
                "abstract": False,
                "swappable": "TENXYTE_PERMISSION_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, related_name="roles", to=settings.TENXYTE_PERMISSION_MODEL),
                ),
            ],
            options={
                "db_table": "roles",
                "ordering": ["name"],
                "abstract": False,
                "swappable": "TENXYTE_ROLE_MODEL",
            },
        ),
        migrations.CreateModel(
            name="OrganizationRole",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique role code (e.g., 'owner', 'admin', 'member')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System role (owner, admin, member) - cannot be deleted"
                    ),
                ),
                ("is_default", models.BooleanField(default=False, help_text="Assigned automatically to new members")),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of permission codes (e.g., ['org.members.invite', 'org.settings.read'])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organization_roles",
                "ordering": ["name"],
                "abstract": False,
                "swappable": "TENXYTE_ORGANIZATION_ROLE_MODEL",
            },
        ),
        # Attach roles & permissions to User
        migrations.AddField(
            model_name="user",
            name="direct_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="users_direct", to=settings.TENXYTE_PERMISSION_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(blank=True, related_name="users", to=settings.TENXYTE_ROLE_MODEL),
        ),
    ]
