# Generated by Django 6.0.2 on 2026-02-26 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0008_merge_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                ("agent_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspendu (automatique)"),
                            ("REVOKED", "Révoqué (manuel)"),
                            ("EXPIRED", "Expiré"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "suspended_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RATE_LIMIT", "Rate Limit dépassé"),
                            ("ANOMALY", "Comportement anormal détecté"),
                            ("MANUAL", "Révocation manuelle"),
                            ("HEARTBEAT_MISSING", "Heartbeat manquant"),
                            ("BUDGET_EXCEEDED", "Budget dépassé"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("max_requests_per_minute", models.PositiveIntegerField(default=60)),
                ("max_requests_total", models.PositiveIntegerField(default=1000)),
                ("current_request_count", models.PositiveIntegerField(default=0)),
                ("max_failed_requests", models.PositiveIntegerField(default=10)),
                ("current_failed_count", models.PositiveIntegerField(default=0)),
                ("heartbeat_required_every", models.PositiveIntegerField(blank=True, null=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("budget_limit_usd", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("current_spend_usd", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tokens",
                        to=settings.TENXYTE_APPLICATION_MODEL,
                    ),
                ),
                (
                    "granted_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="agent_tokens", to=settings.TENXYTE_PERMISSION_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_tokens",
                        to=settings.TENXYTE_ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_agent_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_tokens",
            },
        ),
        migrations.CreateModel(
            name="AgentPendingAction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("permission_requested", models.CharField(max_length=100)),
                ("endpoint", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                ("confirmation_token", models.CharField(db_index=True, max_length=128, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("denied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("prompt_trace_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "agent_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_actions",
                        to="tenxyte.agenttoken",
                    ),
                ),
            ],
            options={
                "db_table": "agent_pending_actions",
            },
        ),
        migrations.AddIndex(
            model_name="agenttoken",
            index=models.Index(fields=["status", "expires_at"], name="agent_token_status_883503_idx"),
        ),
        migrations.AddIndex(
            model_name="agenttoken",
            index=models.Index(fields=["triggered_by", "status"], name="agent_token_trigger_18d25e_idx"),
        ),
    ]
