# Generated by Django 6.0.2 on 2026-02-20 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Organization name", max_length=200)),
                ("slug", models.SlugField(help_text="URL-safe unique identifier", max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Flexible JSON metadata for custom fields"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_members",
                    models.PositiveIntegerField(default=0, help_text="Maximum members allowed (0 = unlimited)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organizations",
                "ordering": ["name"],
                "abstract": False,
                "swappable": "TENXYTE_ORGANIZATION_MODEL",
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Invitation Pending"), ("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organization_memberships",
                "ordering": ["-created_at"],
                "abstract": False,
                "swappable": "TENXYTE_ORGANIZATION_MEMBERSHIP_MODEL",
            },
        ),
        migrations.CreateModel(
            name="OrganizationRole",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique role code (e.g., 'owner', 'admin', 'member')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System role (owner, admin, member) - cannot be deleted"
                    ),
                ),
                ("is_default", models.BooleanField(default=False, help_text="Assigned automatically to new members")),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of permission codes (e.g., ['org.members.invite', 'org.settings.read'])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organization_roles",
                "ordering": ["name"],
                "abstract": False,
                "swappable": "TENXYTE_ORGANIZATION_ROLE_MODEL",
            },
        ),
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(help_text="Email of invitee", max_length=254)),
                (
                    "token",
                    models.CharField(
                        db_index=True, help_text="Secure token for accepting invitation", max_length=64, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="Invitation expiry date")),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "organization_invitations",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.RenameIndex(
            model_name="accountdeletionrequest",
            new_name="account_del_user_id_85393b_idx",
            old_name="account_del_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="accountdeletionrequest",
            new_name="account_del_status_966c21_idx",
            old_name="account_del_status_grace_idx",
        ),
        migrations.RenameIndex(
            model_name="accountdeletionrequest",
            new_name="account_del_confirm_6a5fb8_idx",
            old_name="account_del_token_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="anonymization_token",
            field=models.CharField(
                blank=True,
                help_text="Token used to identify anonymized accounts for audit purposes.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(
                default=False, help_text="Permanent ban (manual admin action). Cannot be auto-lifted."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Soft delete for GDPR compliance. Account is anonymized but kept for audit."
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent organization (null = root organization)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to=settings.TENXYTE_ORGANIZATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_org_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.TENXYTE_ORGANIZATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="org_memberships", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="role",
            field=models.ForeignKey(
                help_text="PROTECT: cannot delete a role while it's assigned",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to=settings.TENXYTE_ORGANIZATION_ROLE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="invited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_org_invitations_pending",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to=settings.TENXYTE_ORGANIZATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="role",
            field=models.ForeignKey(
                help_text="Role to assign upon acceptance",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.TENXYTE_ORGANIZATION_ROLE_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["slug"], name="organizatio_slug_5b8b37_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["parent", "is_active"], name="organizatio_parent__d85208_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(fields=["user", "organization", "status"], name="organizatio_user_id_3c4cbe_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(fields=["organization", "status"], name="organizatio_organiz_33b363_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="organizationmembership",
            unique_together={("user", "organization")},
        ),
        migrations.AddIndex(
            model_name="organizationinvitation",
            index=models.Index(fields=["token"], name="organizatio_token_779f11_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationinvitation",
            index=models.Index(fields=["organization", "status"], name="organizatio_organiz_8a5de2_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationinvitation",
            index=models.Index(fields=["email", "status"], name="organizatio_email_e4e3d6_idx"),
        ),
    ]
