# Generated by Django 6.0.2 on 2026-02-26 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0002_agenttoken_agentpendingaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="agent_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="tenxyte.agenttoken",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="on_behalf_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs_agent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
