# Generated by Django 6.0.2 on 2026-02-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0003_auditlog_agent_token_auditlog_on_behalf_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="prompt_trace_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("login_failed", "Login Failed"),
                    ("logout", "Logout"),
                    ("logout_all", "Logout All Devices"),
                    ("token_refresh", "Token Refresh"),
                    ("password_change", "Password Changed"),
                    ("password_reset_request", "Password Reset Requested"),
                    ("password_reset_complete", "Password Reset Completed"),
                    ("2fa_enabled", "2FA Enabled"),
                    ("2fa_disabled", "2FA Disabled"),
                    ("2fa_backup_used", "2FA Backup Code Used"),
                    ("account_created", "Account Created"),
                    ("account_locked", "Account Locked"),
                    ("account_unlocked", "Account Unlocked"),
                    ("email_verified", "Email Verified"),
                    ("phone_verified", "Phone Verified"),
                    ("role_assigned", "Role Assigned"),
                    ("role_removed", "Role Removed"),
                    ("permission_changed", "Permission Changed"),
                    ("app_created", "Application Created"),
                    ("app_credentials_regenerated", "Application Credentials Regenerated"),
                    ("account_deleted", "Account Deleted"),
                    ("suspicious_activity", "Suspicious Activity Detected"),
                    ("session_limit_exceeded", "Session Limit Exceeded"),
                    ("device_limit_exceeded", "Device Limit Exceeded"),
                    ("new_device_detected", "New Device Detected"),
                    ("agent_action", "Agent Action Executed"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
