# Generated by Tenxyte — R20: Migration decomposition
# Security audit models: AuditLog, AccountDeletionRequest

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0001_core"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("login_failed", "Login Failed"),
                            ("logout", "Logout"),
                            ("logout_all", "Logout All Devices"),
                            ("token_refresh", "Token Refresh"),
                            ("password_change", "Password Changed"),
                            ("password_reset_request", "Password Reset Requested"),
                            ("password_reset_complete", "Password Reset Completed"),
                            ("2fa_enabled", "2FA Enabled"),
                            ("2fa_disabled", "2FA Disabled"),
                            ("2fa_backup_used", "2FA Backup Code Used"),
                            ("account_created", "Account Created"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("email_verified", "Email Verified"),
                            ("phone_verified", "Phone Verified"),
                            ("role_assigned", "Role Assigned"),
                            ("role_removed", "Role Removed"),
                            ("permission_changed", "Permission Changed"),
                            ("app_created", "Application Created"),
                            ("app_credentials_regenerated", "Application Credentials Regenerated"),
                            ("account_deleted", "Account Deleted"),
                            ("suspicious_activity", "Suspicious Activity Detected"),
                            ("session_limit_exceeded", "Session Limit Exceeded"),
                            ("device_limit_exceeded", "Device Limit Exceeded"),
                            ("new_device_detected", "New Device Detected"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.TENXYTE_APPLICATION_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmation_sent", "Confirmation Sent"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "confirmation_token",
                    models.CharField(help_text="Secure token for email confirmation", max_length=64, unique=True),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("grace_period_ends_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True, help_text="Optional reason for deletion request")),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_deletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "account_deletion_requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="accountdeletionrequest",
            index=models.Index(fields=["user", "status"], name="account_del_user_id_85393b_idx"),
        ),
        migrations.AddIndex(
            model_name="accountdeletionrequest",
            index=models.Index(fields=["status", "grace_period_ends_at"], name="account_del_status_966c21_idx"),
        ),
        migrations.AddIndex(
            model_name="accountdeletionrequest",
            index=models.Index(fields=["confirmation_token"], name="account_del_confirm_6a5fb8_idx"),
        ),
    ]
