# Generated by Django 6.0.2 on 2026-03-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0007_clear_oauth_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_restricted",
            field=models.BooleanField(
                default=False,
                help_text="Marque le compte comme restreint (Art. 18 RGPD). Limite le traitement des données sans suppression.",
            ),
        ),
        migrations.AlterField(
            model_name="agenttoken",
            name="token",
            field=models.CharField(
                db_index=True,
                help_text="SHA-256 hash of the raw agent token. Never store the raw value.",
                max_length=128,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="anonymization_token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
