# Generated by Tenxyte — R20: Migration decomposition
# Merge migration: unifies all 7 thematic initial migrations into one
# leaf before incremental migrations (0009+) continue from here.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0001_core"),
        ("tenxyte", "0002_rbac"),
        ("tenxyte", "0003_auth"),
        ("tenxyte", "0004_security"),
        ("tenxyte", "0005_organizations"),
        ("tenxyte", "0006_social"),
        ("tenxyte", "0007_webauthn"),
    ]

    operations = []
