# Generated by Django 6.0.2 on 2026-03-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0008_user_is_restricted_alter_agenttoken_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiclinktoken",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
