# Generated by Django 6.0.2 on 2026-03-03 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0009_magiclinktoken_user_agent_alter_user_totp_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyModel1",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to=settings.TENXYTE_ORGANIZATION_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DummyModel2",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to=settings.TENXYTE_ORGANIZATION_MODEL,
                    ),
                ),
            ],
        ),
    ]
