# Generated by Django 6.0.2 on 2026-03-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0009_magiclinktoken_user_agent_alter_user_totp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
