# Generated by Django 6.0.2 on 2026-03-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0009_magiclinktoken_user_agent_alter_user_totp_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyModel1",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DummyModel2",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
