# Generated by Django 6.0.2 on 2026-03-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0010_permission_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="custom_fields",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(blank=True, default="", max_length=63),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, db_index=True, max_length=191, null=True, unique=True),
        ),
    ]
