# Generated by Django 6.0.3 on 2026-03-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0011_add_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="redirect_uris",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allowed redirect URIs for OAuth flows. Empty list permits all.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lockout_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Consecutive lockout count for exponential backoff."
            ),
        ),
    ]
