# Generated by Django 5.2.14 on 2026-05-27 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0012_application_redirect_uris_user_lockout_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refresh_tokens",
                to=settings.TENXYTE_APPLICATION_MODEL,
            ),
        ),
    ]
