# Generated by Django 6.0.2 on 2026-03-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenxyte", "0016_dummymodel1_dummymodel2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dummymodel2",
            name="organization",
        ),
        migrations.DeleteModel(
            name="DummyModel1",
        ),
        migrations.DeleteModel(
            name="DummyModel2",
        ),
    ]
